export enum IntentType {

  GREETING = 'GREETING',

  COUNTRY = 'COUNTRY',

  WEATHER = 'WEATHER',

  CURRENCY = 'CURRENCY',

  DICTIONARY = 'DICTIONARY',

  JOKE = 'JOKE',

  PROGRAMMING = 'PROGRAMMING',

  TECHNOLOGY = 'TECHNOLOGY',

  COURSE = 'COURSE',

  UNKNOWN = 'UNKNOWN',

  CD_ABOUT = 'CD_ABOUT',

  CD_WHY_CHOOSE = 'CD_WHY_CHOOSE',

  CD_COURSE_INQUIRY = 'CD_COURSE_INQUIRY',

  CD_COURSE_FULLSTACK = 'CD_COURSE_FULLSTACK',

  CD_COURSE_DATASCIENCE = 'CD_COURSE_DATASCIENCE',

  CD_COURSE_CLOUD = 'CD_COURSE_CLOUD',

  CD_COURSE_AI = 'CD_COURSE_AI',

  CD_TRAINER = 'CD_TRAINER',

  CD_BATCH = 'CD_BATCH',

  CD_MODE = 'CD_MODE',

  CD_ROADMAP = 'CD_ROADMAP',

  CD_BEGINNER = 'CD_BEGINNER',

  CD_PLACEMENT = 'CD_PLACEMENT',

  CD_AI_ML = 'CD_AI_ML',

  CD_FAQ = 'CD_FAQ',

  CD_RESTRICTED = 'CD_RESTRICTED',

  CD_CONTACT = 'CD_CONTACT',

  CD_ENROLL = 'CD_ENROLL',
}